apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-class
  labels:
    app: my-class
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-class
  template:
    metadata:
      labels:
        app: my-class
    spec:
      containers:
      - name: my-class
        image: node:14
        ports:
        - containerPort: 8080
          resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
