name: eks-ci-cd
on:
  push:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/checkout@v3
      - uses: aws-actions/aws-cli@v3
        with:
          aws-region: ${{ secrets.$AWS_REGION }}
      - run: aws configure set aws_access_key_id ${{ secrets.$AWS_ACCESS_KEY_ID }}
      - run: aws configure set aws_secret_access_key ${{ secrets.$AWS_SECRET_ACCESS_KEY }}

  # (Optional) Terraform deployment job
  provision-eks:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: hashicorp/terraform@v1.3.2
        with:
          backend-config: # Configure Terraform backend if needed

  build-push-images:
    runs-on: ubuntu-latest
    needs: setup  # Only run after setup job
    steps:
      - uses: actions/checkout@v3
      - name: Login to ECR
        run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY
        env:
          AWS_REGION: ${{ secrets.$AWS_REGION }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      - name: Build and push service image
        run: docker build -t $ECR_REPOSITORY:service .  # Replace with your Dockerfile location
        and: success()
      - name: Build and push cronjob image
        run: docker build -t $ECR_REPOSITORY:cronjob .  # Replace with your Dockerfile location
        and: success()
      - name: Push service image
        run: docker push $ECR_REPOSITORY:service
      - name: Push cronjob image
        run: docker push $ECR_REPOSITORY:cronjob

  deploy-services:
    runs-on: ubuntu-latest
    needs: [ build-push-images, setup ]  # Only run after build and setup jobs
    steps:
      - uses: aws-actions/eks-deploy@v1.21.0
        with:
          cluster-name: ${{ secrets.$EKS_CLUSTER_NAME }}
          region: ${{ secrets.$AWS_REGION }}
          namespace: descomplica-class  # Replace with your namespace
          kubeconfig: ${{ secrets.KUBECONFIG_FILE }}  # Path to kubeconfig file (generated during setup)
          force-deploy: true  # Optional: Update deployments even if no changes are detected

workflow_dispatch:
  inputs:
    manual:
      type: boolean
      description: "Run the workflow manually"
